"""Durable runtime store records and persistence."""

from __future__ import annotations

from coding_agent.stores.rtstore.harness import (
    DEFAULT_HARNESS_PROJECTION as DEFAULT_HARNESS_PROJECTION,
    AuthoritativeCommit as AuthoritativeCommit,
    AuthoritativeUnitOfWork as AuthoritativeUnitOfWork,
    CommandMailboxEntry as CommandMailboxEntry,
    ChildBindingConflictError as ChildBindingConflictError,
    ChildExecutionBinding as ChildExecutionBinding,
    CommandMailboxSnapshot as CommandMailboxSnapshot,
    AuthoritativeWriteRefusedError as AuthoritativeWriteRefusedError,
    CommandDispositionConflictError as CommandDispositionConflictError,
    RuntimeCommandAdmission as RuntimeCommandAdmission,
    RuntimeCommandAdmissionConflictError as RuntimeCommandAdmissionConflictError,
    CursorEpochMismatchError as CursorEpochMismatchError,
    EffectMutationConflictError as EffectMutationConflictError,
    EffectReconciliationEvidence as EffectReconciliationEvidence,
    ExecutorAttemptConflictError as ExecutorAttemptConflictError,
    ExecutorAttemptStatus as ExecutorAttemptStatus,
    ExecutorAttemptRecord as ExecutorAttemptRecord,
    EffectLedgerSlot as EffectLedgerSlot,
    EventRecord as EventRecord,
    InvalidDispatchAuthorizationError as InvalidDispatchAuthorizationError,
    InvalidReconciliationPreconditionError as InvalidReconciliationPreconditionError,
    KeyExpiredError as KeyExpiredError,
    RecoveredChildExecutionLease as RecoveredChildExecutionLease,
    RecoveredChildControlState as RecoveredChildControlState,
    RecoveryLeaseConflictError as RecoveryLeaseConflictError,
    RecoveryGuardKind as RecoveryGuardKind,
    RecoveryTransitionGuard as RecoveryTransitionGuard,
    RecoveryEvidenceConflictError as RecoveryEvidenceConflictError,
    MailboxDispositionSlot as MailboxDispositionSlot,
    OperationReceiptSlot as OperationReceiptSlot,
    ProjectionCursor as ProjectionCursor,
    RawCursor as RawCursor,
    RetentionFloorReplay as RetentionFloorReplay,
    SessionFactSourceState as SessionFactSourceState,
    TrustedHandoff as TrustedHandoff,
    StateVersionConflictError as StateVersionConflictError,
    TransitionFingerprintMismatchError as TransitionFingerprintMismatchError,
    StaleMailboxCutError as StaleMailboxCutError,
    StaleRecoveryGuardError as StaleRecoveryGuardError,
    UnstartedDispatchCloseoutGuard as UnstartedDispatchCloseoutGuard,
    unstarted_dispatch_closeout_guard_payload as unstarted_dispatch_closeout_guard_payload,
    _EFFECT_STATUS_RANKS as _EFFECT_STATUS_RANKS,
    _plain_json as _plain_json,
    assert_projection_binding as assert_projection_binding,
    assert_raw_cursor_not_expired as assert_raw_cursor_not_expired,
    assert_recovery_guard_shape as assert_recovery_guard_shape,
    assert_trusted_handoff as assert_trusted_handoff,
    child_execution_binding_from_payload as child_execution_binding_from_payload,
    child_execution_binding_payload as child_execution_binding_payload,
    recovered_child_lease_payload as recovered_child_lease_payload,
    recovered_child_lease_from_payload as recovered_child_lease_from_payload,
    effect_status_may_replace as effect_status_may_replace,
    effect_slot_from_mutation as effect_slot_from_mutation,
    effect_status_rank as effect_status_rank,
    format_u64 as format_u64,
    mailbox_slot_from_disposition as mailbox_slot_from_disposition,
    runtime_command_from_mailbox_payload as runtime_command_from_mailbox_payload,
    runtime_command_invalidates_dispatch as runtime_command_invalidates_dispatch,
    runtime_command_mailbox_payload as runtime_command_mailbox_payload,
    runtime_command_targets as runtime_command_targets,
    validate_new_runtime_command_target as validate_new_runtime_command_target,
    validate_recovery_approval_refresh as validate_recovery_approval_refresh,
    adopt_parent_settlement_receipt as adopt_parent_settlement_receipt,
    state_value_with_reconciled_effect as state_value_with_reconciled_effect,
    runtime_command_mailbox_payloads_equal as runtime_command_mailbox_payloads_equal,
    parse_u64 as parse_u64,
    receipt_generation_may_replace as receipt_generation_may_replace,
    stored_trusted_handoff as stored_trusted_handoff,
    snapshot_transition_unit as snapshot_transition_unit,
    transition_commit_from_payload as transition_commit_from_payload,
    transition_commit_payload as transition_commit_payload,
    transition_mutation_fingerprint as transition_mutation_fingerprint,
)
from coding_agent.stores.rtstore.jsonl import JSONLRuntimeStore as JSONLRuntimeStore
from coding_agent.stores.rtstore.payload import (
    _agent_run_from_payload as _agent_run_from_payload,
    _agent_run_to_payload as _agent_run_to_payload,
    _datetime_to_json as _datetime_to_json,
    _interaction_from_payload as _interaction_from_payload,
    _interaction_to_payload as _interaction_to_payload,
    _message_snapshot_from_payload as _message_snapshot_from_payload,
    _message_snapshot_to_payload as _message_snapshot_to_payload,
    _optional_datetime as _optional_datetime,
    _optional_payload_datetime as _optional_payload_datetime,
    _optional_payload_str as _optional_payload_str,
    _optional_str as _optional_str,
    _required_datetime as _required_datetime,
    _required_int as _required_int,
    _required_json_object as _required_json_object,
    _required_message_list as _required_message_list,
    _required_payload_datetime as _required_payload_datetime,
    _required_payload_int as _required_payload_int,
    _required_payload_json_object as _required_payload_json_object,
    _required_payload_message_list as _required_payload_message_list,
    _required_payload_str as _required_payload_str,
    _required_str as _required_str,
    _runtime_event_from_payload as _runtime_event_from_payload,
    _runtime_event_to_payload as _runtime_event_to_payload,
)
from coding_agent.stores.rtstore.pg import PGRuntimeStore as PGRuntimeStore
from coding_agent.stores.rtstore.pg_codec import (
    _agent_run_from_row as _agent_run_from_row,
    _interaction_from_row as _interaction_from_row,
    _message_snapshot_from_row as _message_snapshot_from_row,
    _required_row as _required_row,
    _runtime_event_from_row as _runtime_event_from_row,
    _operation_state_from_row as _operation_state_from_row,
    _transition_receipt_from_row as _transition_receipt_from_row,
)
from coding_agent.stores.rtstore.json_types import (
    JSONObject as JSONObject,
    JSONScalar as JSONScalar,
    JSONValue as JSONValue,
)
from coding_agent.stores.rtstore.records import (
    AgentInteractionRecord as AgentInteractionRecord,
    AgentRunRecord as AgentRunRecord,
    RunMessageSnapshotRecord as RunMessageSnapshotRecord,
    RuntimeEventRecord as RuntimeEventRecord,
)
from coding_agent.stores.rtstore.sqlite import SQLiteRuntimeStore as SQLiteRuntimeStore
from coding_agent.stores.rtstore.sqlite_codec import (
    _agent_run_from_sqlite_row as _agent_run_from_sqlite_row,
    _agent_run_sqlite_values as _agent_run_sqlite_values,
    _operation_state_from_sqlite_row as _operation_state_from_sqlite_row,
    _interaction_from_sqlite_row as _interaction_from_sqlite_row,
    _interaction_sqlite_values as _interaction_sqlite_values,
    _json_from_sql as _json_from_sql,
    _json_object_from_sql as _json_object_from_sql,
    _json_to_sql as _json_to_sql,
    _message_list_from_sql as _message_list_from_sql,
    _message_snapshot_from_sqlite_row as _message_snapshot_from_sqlite_row,
    _runtime_event_from_sqlite_row as _runtime_event_from_sqlite_row,
    _transition_receipt_from_sqlite_row as _transition_receipt_from_sqlite_row,
    _sqlite_optional_datetime as _sqlite_optional_datetime,
    _sqlite_optional_int as _sqlite_optional_int,
    _sqlite_optional_str as _sqlite_optional_str,
    _sqlite_required_datetime as _sqlite_required_datetime,
    _sqlite_required_int as _sqlite_required_int,
    _sqlite_required_str as _sqlite_required_str,
    _sqlite_value as _sqlite_value,
)
from coding_agent.stores.rtstore.validate import (
    _normalize_optional_error as _normalize_optional_error,
    _require_datetime as _require_datetime,
    _require_json_object as _require_json_object,
    _require_non_empty as _require_non_empty,
    _require_non_negative_int as _require_non_negative_int,
    _require_positive_int as _require_positive_int,
)

__all__ = [
    "AgentInteractionRecord",
    "AgentRunRecord",
    "AuthoritativeCommit",
    "AuthoritativeUnitOfWork",
    "CommandMailboxEntry",
    "ChildBindingConflictError",
    "ChildExecutionBinding",
    "CommandMailboxSnapshot",
    "CommandDispositionConflictError",
    "RuntimeCommandAdmission",
    "RuntimeCommandAdmissionConflictError",
    "AuthoritativeWriteRefusedError",
    "CursorEpochMismatchError",
    "DEFAULT_HARNESS_PROJECTION",
    "adopt_parent_settlement_receipt",
    "EffectMutationConflictError",
    "EffectReconciliationEvidence",
    "ExecutorAttemptConflictError",
    "ExecutorAttemptStatus",
    "ExecutorAttemptRecord",
    "EffectLedgerSlot",
    "EventRecord",
    "JSONLRuntimeStore",
    "KeyExpiredError",
    "InvalidReconciliationPreconditionError",
    "RecoveryEvidenceConflictError",
    "RecoveredChildExecutionLease",
    "RecoveredChildControlState",
    "RecoveryGuardKind",
    "RecoveryLeaseConflictError",
    "RecoveryTransitionGuard",
    "MailboxDispositionSlot",
    "OperationReceiptSlot",
    "PGRuntimeStore",
    "ProjectionCursor",
    "RawCursor",
    "RetentionFloorReplay",
    "RunMessageSnapshotRecord",
    "RuntimeEventRecord",
    "SQLiteRuntimeStore",
    "SessionFactSourceState",
    "StateVersionConflictError",
    "TransitionFingerprintMismatchError",
    "StaleRecoveryGuardError",
    "UnstartedDispatchCloseoutGuard",
    "state_value_with_reconciled_effect",
    "TrustedHandoff",
    "format_u64",
    "parse_u64",
]
