from importlib import import_module
from typing import Any

_EXPORTS = {
    "BeeCommandIntentResolutionStatus": "command_bridge",
    "BeeCommandIntentPlanStatus": "command_bridge",
    "BeeValidationBridgeStatus": "command_bridge",
    "BeeNodeCompletionStatus": "command_bridge",
    "BeeCommandIntentResolution": "command_bridge",
    "BeeCommandIntentPlan": "command_bridge",
    "BeeValidationBridgeResult": "command_bridge",
    "BeeNodeCompletionEvidence": "command_bridge",
    "BeeNodeCompletionDecision": "command_bridge",
    "resolve_bee_command_intent": "command_bridge",
    "plan_bee_command_intent": "command_bridge",
    "is_authorized_bee_command_plan": "command_bridge",
    "run_bee_validation_node": "command_bridge",
    "complete_bee_node_from_bridge_result": "command_bridge",
    "BeeLaunchSource": "launch",
    "BeeLaunchStatus": "launch",
    "BeeLaunchStore": "launch",
    "BeeTaskLaunchStore": "launch",
    "BeeScheduleTriggerStore": "launch",
    "BeeLaunchTopicStore": "launch",
    "BeeLaunchRecord": "launch",
    "BeeLaunchRequest": "launch",
    "BeeTemplateResolution": "launch",
    "BeeInputBinding": "launch",
    "BeeLaunchPlan": "launch",
    "BeeLaunchResult": "launch",
    "PGBeeLaunchStore": "launch",
    "build_bee_launch_plan": "launch",
    "BeeLaunchOrchestrator": "launch",
    "ScheduledBeeLaunchOrchestrator": "launch",
    "ProactiveBeeLaunchOrchestrator": "launch",
    "BeeTaskLifecycleController": "launch",
    "BeeTaskStatus": "runtime",
    "BeeNodeStatus": "runtime",
    "BEE_TASK_STARTED": "runtime",
    "BEE_TASK_FINALIZED": "runtime",
    "BEE_TASK_ABORTED": "runtime",
    "BeeTopicAnchorStore": "runtime",
    "BeeTaskPlannerStore": "runtime",
    "BeeTaskRecord": "runtime",
    "BeeNodeRecord": "runtime",
    "BeeNodeLaunchIntent": "runtime",
    "BeeTopicBinding": "runtime",
    "BeeNodeManifest": "runtime",
    "BeeTaskManifest": "runtime",
    "parse_bee_task_manifest": "runtime",
    "PGBeeTaskStore": "runtime",
    "BeeTaskLifecycle": "runtime",
    "BeeTaskPlanner": "runtime",
    "build_bee_launch_metadata": "runtime",
    "BeeTemplatePackSource": "template_pack",
    "BeePackManifest": "template_pack",
    "BeeTemplatePack": "template_pack",
    "BeePackSummary": "template_pack",
    "BeePackTemplateSummary": "template_pack",
    "BeePackTemplateProvenance": "template_pack",
    "BeePackCompatibilityCheck": "template_pack",
    "BeePackCompatibilityFinding": "template_pack",
    "BeePackTemplateCompatibilitySummary": "template_pack",
    "BeePackCompatibilityReport": "template_pack",
    "BeePackDryRunPlan": "template_pack",
    "BeePackRegistry": "template_pack",
    "build_bee_pack_dry_run_plan": "template_pack",
    "validate_bee_pack_compatibility": "template_pack",
    "load_bee_template_pack": "template_pack",
    "BeeWorkspaceTemplate": "workspace",
    "BeeWorkspaceRunNode": "workspace",
    "BeeWorkspaceExecutorRunArtifact": "workspace",
    "BeeWorkspaceRunArtifacts": "workspace",
    "BeeWorkspaceRunArtifactPaths": "workspace",
    "BeeWorkspaceRunArtifactRecord": "workspace",
    "BeeWorkspaceCommandIntent": "workspace",
    "discover_bee_workspace_templates": "workspace",
    "load_bee_workspace_template": "workspace",
    "build_bee_manifest_from_workspace_template": "workspace",
    "load_bee_workspace_command_intents": "workspace",
    "discover_bee_workspace_run_artifacts": "workspace",
    "write_bee_workspace_run_artifacts": "workspace",
}

__all__ = tuple(_EXPORTS)


def __getattr__(name: str) -> Any:
    module_name = _EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(f"{__name__}.{module_name}")
    value = getattr(module, name)
    globals()[name] = value
    return value
