from __future__ import annotations

from typing import Protocol, runtime_checkable

from .context import AgentRunContext, ContextBudget
from .contracts import (
    ApprovalResolved,
    ApprovalSettlement,
    AppliedCommandDisposition,
    BlockedAction,
    BlockedOutcome,
    CancellationToken,
    CancelledOutcome,
    CASConflictCommitResult,
    CommandDisposition,
    CommandDispositionKind,
    CommitPort,
    CommitReconciliationRequest,
    CommitReconciliationResult,
    CommitRef,
    CommitResultKind,
    CommitSettlementRequest,
    CommitSettlementResult,
    CommitTransitionRequest,
    CommitTransitionResult,
    CommittedCommitResult,
    CommittedFactNotice,
    CommittedFactSink,
    CompletedOutcome,
    ControlGeneration,
    ControlProbe,
    ControlSnapshot,
    DeliveryFailure,
    DispatchAuthorizationRequest,
    DispatchAuthorizationResult,
    DispatchAuthorizedResult,
    DispatchPermit,
    EffectCompletedResult,
    EffectExecutionResult,
    EffectExecutor,
    EffectFailedResult,
    EffectIndeterminateResult,
    EffectMutation,
    EffectPlan,
    EffectReference,
    EffectSettled,
    EffectSettlement,
    EffectSettlementOutcome,
    EffectStatus,
    EngineStepInput,
    EngineStepRequest,
    ExactReplayCommitResult,
    FailedOutcome,
    FailureReport,
    FrameSink,
    Initial,
    InvalidTransitionCommitResult,
    JSONValue,
    ModelAdapter,
    ModelGenerationAction,
    ModelGenerationCompleted,
    ModelGenerationResult,
    ModelRequest,
    ModelToolCall,
    ModelUsage,
    NextAction,
    OperationStateCAS,
    OperationStateVersion,
    PendingFact,
    PreparedEffectAction,
    PreparedEffectActionKind,
    ProviderStopMetadata,
    ReconciliationOutcome,
    ReconciliationRecord,
    RejectedCommandDisposition,
    RoundLimitOutcome,
    RunSegmentRequest,
    RuntimeCommand,
    SafeYieldAction,
    SafeYieldOutcome,
    SegmentOutcome,
    SegmentOutcomeKind,
    Settlement,
    StaleMailboxCutCommitResult,
    StaleOwnerCommitResult,
    StorageFailureCommitResult,
    StreamFrame,
    StreamFrameKind,
    SupersededCommandDisposition,
    TerminalAction,
    TransitionProposal,
    TransitionReceipt,
)
from .coordinator import SegmentCoordinator
from .engine import AgentEngine
from .hook_runtime import HookRuntime
from .hookspecs import HOOK_SPECS, HookSpec
from .messages import (
    DuplicateRuntimeMessageError,
    InMemoryRuntimeMessageBus,
    RuntimeMessage,
    RuntimeMessageBatch,
    RuntimeMessageBus,
    RuntimeMessageCursor,
    RuntimeMessageKind,
    SequencedRuntimeMessage,
)


@runtime_checkable
class Lifecycle(Protocol):
    async def on_startup(self) -> None: ...

    async def on_shutdown(self, timeout: float = 30.0) -> None: ...

    async def health_check(self) -> dict[str, object]: ...

    async def readiness_check(self) -> bool: ...


__all__ = [
    "HOOK_SPECS",
    "AgentEngine",
    "AgentRunContext",
    "ApprovalResolved",
    "ApprovalSettlement",
    "AppliedCommandDisposition",
    "BlockedAction",
    "BlockedOutcome",
    "CASConflictCommitResult",
    "CancellationToken",
    "CancelledOutcome",
    "CommandDisposition",
    "CommandDispositionKind",
    "CommitPort",
    "CommitReconciliationRequest",
    "CommitReconciliationResult",
    "CommitRef",
    "CommitResultKind",
    "CommitSettlementRequest",
    "CommitSettlementResult",
    "CommitTransitionRequest",
    "CommitTransitionResult",
    "CommittedCommitResult",
    "CommittedFactNotice",
    "CommittedFactSink",
    "CompletedOutcome",
    "ContextBudget",
    "ControlGeneration",
    "ControlProbe",
    "ControlSnapshot",
    "DeliveryFailure",
    "DispatchAuthorizationRequest",
    "DispatchAuthorizationResult",
    "DispatchAuthorizedResult",
    "DispatchPermit",
    "DuplicateRuntimeMessageError",
    "EffectCompletedResult",
    "EffectExecutionResult",
    "EffectExecutor",
    "EffectFailedResult",
    "EffectIndeterminateResult",
    "EffectMutation",
    "EffectPlan",
    "EffectReference",
    "EffectSettled",
    "EffectSettlement",
    "EffectSettlementOutcome",
    "EffectStatus",
    "EngineStepInput",
    "EngineStepRequest",
    "ExactReplayCommitResult",
    "FailedOutcome",
    "FailureReport",
    "FrameSink",
    "HookRuntime",
    "HookSpec",
    "InMemoryRuntimeMessageBus",
    "Initial",
    "InvalidTransitionCommitResult",
    "JSONValue",
    "Lifecycle",
    "ModelAdapter",
    "ModelGenerationAction",
    "ModelGenerationCompleted",
    "ModelGenerationResult",
    "ModelRequest",
    "ModelToolCall",
    "ModelUsage",
    "NextAction",
    "OperationStateCAS",
    "OperationStateVersion",
    "PendingFact",
    "PreparedEffectAction",
    "PreparedEffectActionKind",
    "ProviderStopMetadata",
    "ReconciliationOutcome",
    "ReconciliationRecord",
    "RejectedCommandDisposition",
    "RoundLimitOutcome",
    "RunSegmentRequest",
    "RuntimeCommand",
    "RuntimeMessage",
    "RuntimeMessageBatch",
    "RuntimeMessageBus",
    "RuntimeMessageCursor",
    "RuntimeMessageKind",
    "SafeYieldAction",
    "SafeYieldOutcome",
    "SegmentCoordinator",
    "SegmentOutcome",
    "SegmentOutcomeKind",
    "SequencedRuntimeMessage",
    "Settlement",
    "StaleMailboxCutCommitResult",
    "StaleOwnerCommitResult",
    "StorageFailureCommitResult",
    "StreamFrame",
    "StreamFrameKind",
    "SupersededCommandDisposition",
    "TerminalAction",
    "TransitionProposal",
    "TransitionReceipt",
]
