"""HTTP server constants kept on the stable http_server module."""

from __future__ import annotations

APPROVAL_TIMEOUT_SECONDS = 120
SESSION_IDLE_TIMEOUT_MINUTES = 30
WORKER_STALE_AFTER_SECONDS = 60
WORKER_OFFLINE_AFTER_SECONDS = 300
_SERVER_CONFIG_ENV = "CODING_AGENT_SERVER_CONFIG"
_CORS_ORIGINS_ENV = "CODING_AGENT_CORS_ORIGINS"
_WEBUI_DIST_DIR_ENV = "WEBUI_DIST_DIR"
