apiVersion: v1
kind: PersistentVolume
metadata:
  name: eval-results-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/Users/kina/Code/Agent/Coding-Agent-Loop/agent-coding-loop/eval-results"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eval-results-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
